# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23e85e578193758014c18ed8559c738c406bdb71839fc99e621f0ee9c1ffc58433adc762ab22d726ffc677e06d2952cc63ae7908a97ece1b41f35c95b785f92e

test:
  secret_key_base: 44ad373c0e29d81a340474635619726b36a36e1865575a8527760ac36aef28d389866fe1e4728014ab6e5123c0b574799b343c06494a02058847df65d9c7f62d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
